### ISSUE TITLE
Version 1 roadmap

### ISSUE THREAD

**Issue by jt-nti** [hyperledger-labs/fabric-builder-k8s#78]
Starting to think about what needs doing to get to a v1 release. I would like to get the following done, in vague priority order...

- [x] Optionally set service account of chaincode pods #76
- [ ] Add end to end tests #48
- [x] Improve test coverage #28
- [x] New k8s-fabric-peer arm images do not work #74
- [ ] Document required permissions in readme #52
- [x] Document pulling images from registries which require credentials #65
- [ ] Graduate from labs project hyperledger/fabric-rfcs#56
- [x] Define desired kubernetes object names #16

Does that sound reasonable? Is there anything missing?
